Fix the broken components.dir parameter
Nictiz/Nictiz-tooling-testscripts pull request #17
Opened 2022-04-21 08:26 UTC by pieter-edelman-nictiz

... to work again as documented. In addition, remove the reference.dir parameter alltogether, as this cannot really work in relation to how Touchstone works.

2022-04-21 08:54 UTC, jduwel requested changes

2022-04-21 08:54 UTC, jduwel commented on generate/ant/build.xml
> +    <property name="components.dir.abs"       value="${components.dir}"/>
Shouldn't this be
```
<property name="components.dir.abs" location="${components.dir}"/>
```
To properly convert rel to abs path?

2022-04-21 09:29 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +    <property name="components.dir.abs"       value="${components.dir}"/>
Whoops, yes indeed.

2022-05-05 08:26 UTC, jduwel commented on generate/ant/build.xml
> +    <property name="components.dir.abs"       location="${components.dir}"/>
Sorry to go at it again... but: 

I was under the impression that the `.dir` properties were captured as a simple string `@value` (because they can be overruled by derived build scripts, buildproperties, cli, etc.) and then converted to an `@location` (path) in the `.dir.abs` variant. 

So if you use `@location` on both here, is there a necessity for the `.abs` variant? Probably yes, because an overrule from buildproperties or cli is a simple string per definition I think?

Anyways... it probably does not hurt to do it like this, until we find it does hurt later ;)

2022-05-05 08:29 UTC, jduwel approved these changes

2022-05-05 09:41 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +    <property name="components.dir.abs"       location="${components.dir}"/>
Yes, that's the idea ... you can overrule `components.dir` using a setting. I'm not confident that a value with `${input.dir}` will resolve to an absolute path in every situation, so to be on the safe side it's a location here.

2022-05-05 09:42 UTC, merged