Generate loadresources
Nictiz/Nictiz-tooling-testscripts pull request #3
Opened 2020-11-02 09:43 UTC by jduwel

Het 'createTestScript.xsl' wat in diverse _util mappen leefde geïntegreerd in build.

Getest op MP en Questionnaires. Het resultaat moet bij iedere standaard even goed vergeleken worden met wat er al bestond, op zoek naar mogelijke uitzonderingen. 

Voor MP is op het moment de LoadResource gesplitst vanwege performance redenen. Dit zou opgelost kunnen worden door het resultaat van de build te splitsen met een losse XSLT in een custom build.xml.

Het proces gaat uit van een Patient token waarvan de bestandsnaam op 'token.xml' eindigt en waarvan het id met 'Bearer' begint. Dat was impliciet zo, maar is nu even expliciet gemaakt. Alexander heeft dit bij GPData bijvoorbeeld anders gedaan (en vervolgens de bestandsnaam van de token hard gecodeerd), dus dat moet even omgezet worden.

Voor Questionnaires moet er in de projectmap een bestand `build.properties` worden aangemaakt met inhoud:
`loadresources.exclude = _reference/resources/resources-specific`

Het proces is getest met zowel géén `build.properties` als een `build.properties` met alleen `loadresources.exclude =` als inhoud. We zouden dus in iedere src projectmap een lege build.properties kunnen toevoegen om de functie zichtbaarder te maken.

2020-11-03 13:34 UTC, ArdonToonstra commented
Functioneel gezien is deze PR wat mij betreft goed. Voor nu wordt er dus ook voor MP 1 groot loadscript gemaakt? 
Pieter  zou wellicht kunnen kijken met een betere blek naar de wijzigingen op technisch vlak.

2020-11-03 16:47 UTC, pieter-edelman-nictiz requested changes
Ik heb nog wat aanpassingen gedaan in generateLoadResources.xsl, voornamelijk om het wat leesbaarder te maken. Ik heb ook nog een paar vragen geplaatst.
Vooral het punt over de Bearer token vind ik onduidelijk. Nu wordt voor de PUTs de id van de resource gebruikt, geen token. Als je de bijbehorende token voor de patient voor elke resource wil gebruiken, moet je volgens mij wat spannender dingen doen, en anders kunnen de token-resources worden overgeslagen.

2020-11-03 16:47 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +                                <value value="{f:id/@value}"/>
Dit snap ik niet. Dit is niet de patient token, maar de id van de resource die gePUT wordt.

2020-11-03 16:54 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:processing-instruction name="xml-model">href="http://hl7.org/fhir/STU3/testscript.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"</xsl:processing-instruct
Door wat of wie? Dit zorgt ervoor dat het resulterende LoadResources script direct gekoppeld is aan een schema.

2020-11-03 16:55 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +                                <value value="{f:id/@value}"/>
De patient token bestanden zien er bij mijn weten zo uit:
```
<Patient xmlns="http://hl7.org/fhir">
  <id value="Bearer 0dd9618f-ac1f-4ecf-a5a1-440174706ddd"/>
</Patient>
```
Dan klopt het toch?

2020-11-03 16:58 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +    </xd:doc>
Het was een relatief snelle aanpassing van hetgeen al bestond, inclusief dit.

Ik had persoonlijk gekozen voor aanvullen in plaats van weghalen. Maar so be it.

2020-11-03 17:01 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +                    <xsl:sequence select="$fixturesUnfiltered[for $excludedPath in $excludedPaths return (not(contains(document-uri(ancestor::node()),normalize-space($excludedPath))))]"/>
Ik denk dat het door deze aanpassing (het verwijderen van de `if ... then true() else false()`) misgaat als je in build.properties een lege variabele meegeeft. Even testen.

2020-11-03 17:10 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +                    <xsl:sequence select="$fixturesUnfiltered[for $excludedPath in $excludedPaths return (not(contains(document-uri(ancestor::node()),normalize-space($excludedPath))))]"/>
Nee gaat gewoon goed. Nevermind

2020-11-03 17:13 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +    </xsl:template>
Dit ging waarschijnlijk al eerder mis, maar ik zie in het LoadResources van Questionnaires nu meerdere fixtures staan met het id "Task-${task-id}". Dus 
a) er moet misschien toch ergens iets uniek gemaakt worden en 
b) dit gooit hij er niet uit in regel 191 doordat het waarschijnlijk iets moet zijn als:
`<xsl:if test="not(matches($fixtureId, '^[A-Za-z0-9\-\.]{1,64}$'))">`
- maar is het niet beter om 'gewoon' alles wat niet toegestaan is eruit te gooien met een translate()?

2020-11-03 20:45 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +    </xd:doc>
Ik heb er een XML-comment bijgezet, dat hebben we elders ook op die manier gedaan. Ondersteuning voor xd is niet erg sterk heb ik gemerkt en het wordt er naar mijn mening ook niet leesbaarder op.

2020-11-03 20:47 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:processing-instruction name="xml-model">href="http://hl7.org/fhir/STU3/testscript.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"</xsl:processing-instruct
Java validator klaagt er altijd over.

Op https://www.hl7.org/fhir/stu3/xml.html:
> Other processing instructions SHOULD not be included, and SHALL NOT be required to properly understand and/or present the data or narrative of the resource. Applications MAY preserve processing instructions when handling resources, but are not required to do so

2020-11-03 20:50 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +                                <value value="{f:id/@value}"/>
Klopt, maar de id komt hier niet uit die token-fixture, die komt uit de resource die hier gePUT wordt.

2020-11-03 20:57 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +    </xsl:template>
Heb je build.properties goed ingesteld? Dit soort dingen zullen niet voorkomen in resources die door het loadscript afgehandeld worden, dit is uniek voor fixtures waar meerdere versies van bestaan -- die staan bij Questionnaires in resources-specific. Als wel wordt getracht om ze mee te nemen, dan is dat een flinke rode vlag dat je iets verkeerds probeert te doen.

Je hebt gelijk dat de regex aangepast moet worden om op de hele string te matchen.

2020-11-04 07:21 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:processing-instruction name="xml-model">href="http://hl7.org/fhir/STU3/testscript.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"</xsl:processing-instruct
Ok! Was ook al aanwezig, nu weg

2020-11-04 07:22 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +                                <value value="{f:id/@value}"/>
Ah ik zie het. Even kijken hoe het eerst stond. Heb waarschijnlijk iets verkeerd teruggezet na de oeps met het 'dedicated token' idee.

2020-11-04 07:27 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +    </xsl:template>
Dat eerste was het inderdaad.

Regex aangepast

2020-11-04 08:34 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:processing-instruction name="xml-model">href="http://hl7.org/fhir/STU3/testscript.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"</xsl:processing-instruct
Misschien eens aan de kooi gaan rammelen waarom dat zo is eigenlijk.

2020-11-04 08:35 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +                                <value value="{f:id/@value}"/>
Ok, helder. Ik heb nog een kleine aanpassing gedaan zodat de token-fixtures uberhaupt niet worden meegenomen.

2020-11-04 09:39 UTC, merged