Dev 2.3
Nictiz/Nictiz-tooling-testscripts pull request #31
Opened 2022-10-03 14:59 UTC by jduwel

Getest en werkend op een voorbeeld in SelfMeasurements-Test branch

Maakt includes mogelijk met nts:fixtureInclude
Verwijdert Resource.id in batch/transaction
Plaatst of edit entry.fullUrl in batch/transaction
Edit references in batch/transaction

Er zijn veel meer mogelijkheiden wat betreft controleren van fullUrls en referenties en dergelijke in deze Bundles (bijvoorbeeld: relatieve literal references, waarvan de resource niet in de Bundle zit --> error), maar troep in = troep uit (op dit moment althans).

Narratives in Bundles lijken te werken

Todo: README

2022-10-04 14:27 UTC, pieter-edelman-nictiz requested changes
Ja, ziet er op zich goed uit. Ik zou denk ik wel echt een check doen op de aanwezigheid van resources met een letterlijke referentie, maar mss. niet meer dan dat.

2022-10-04 14:27 UTC, pieter-edelman-nictiz commented on generate/xslt/includeFixtures.xsl
> +    <xsl:template match="processing-instruction()" mode="#all" priority="1"/>
Zouden we dit niet op alle fixtures moeten toepassen?

2022-10-04 14:27 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +    <macrodef name="process-references" description="Resolve all includes in referenced files and copy them to the build folder. A check will be done if all referenced files are available.">
This macrodef actually does a bit more than the description suggested and suggests. Proposal:
> Process the fixtures and rules in the _references folder and copy the result to the destination folder. Processing means that the nts:includeFixture tag will be resolved to the referenced file, that a check is done for the existence of fixtures and rules which are referenced from the TestScript, and that rules from the global scope will be included in the output.

2022-10-19 07:41 UTC, jduwel commented on generate/xslt/includeFixtures.xsl
> +    <xsl:import href="https://github.com/Nictiz/HL7-mappings/raw/master/util/uuid.xsl"/>
Ik snap je punt.
Ik heb hem voor nu even vastgezet op een commit (ook 'een manier' van versioneren). Dit bestand gaat niet significant veranderen, want dan valt er nogal veel om, maar a) dat toont het probleem des te meer aan en b) dat is niet iets waar je vanuit zou moeten gaan.
Misschien kunnen we inderdaad kijken of we parallel aan de narrativeGenerator dit ook kunnen versioneren, of de narrativeGenerator 'package' omkatten naar iets als "mappingsUtil"?

2022-10-19 08:14 UTC, jduwel commented
> Ik zou denk ik wel echt een check doen op de aanwezigheid van resources met een letterlijke referentie, maar mss. niet meer dan dat.

Ik kan uit deze opmerking niet per se destilleren wat het verzoek is.
Hij doet nu:
```
<!-- if literal reference that matches a resource in the Bundle -->
<xsl:when test="ancestor::f:Bundle/f:entry/f:resource/f:*/f:id/@value = $referencedId">
```
Maar alleen in fixtures waar een `nts:inlcudeFixture` in aanwezig is (was).
Je zou een waarschuwing willen gooien als er een relatieve letterlijke referentie aanwezig is die dus níet in de Bundle aanwezig is denk ik. Maar dat zou je misschien wel voor álle batch/transaction Bundles willen, niet alleen in die met `nts:inlcudeFixture` aanwezig. En op zo'n moment zou je ook uuid referenties meteen kunnen controleren denk ik.

2022-11-09 13:49 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +    <property name="reference.dir.name"       value="_reference"/>
Maybe it's more descriptive and consistent to call this "reference.subdir"?

2022-11-09 13:51 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +                    <!-- Set this property with random value to skip includeFixtures, for example when fixtures are generated themselves -->
Suggestion:
`<!-- Set this property to 'true' (or any other non-empty value) to skip includeFixtures, for example when fixtures are generated themselves -->`

2022-11-09 13:52 UTC, pieter-edelman-nictiz commented on generate/xslt/includeFixtures.xsl
> +    <xsl:template match="processing-instruction()" mode="#all" priority="1"/>
processFixtures dan?

2022-11-14 12:29 UTC, jduwel commented
Re: build-keten. Ja dit kan veilig voor de narrative plaatsvinden, dat gebeurt nu ook. In de dev map worden de 'definitieve' fixtures samengesteld, waarna de narratives gegenereerd worden. Narratives worden ook in Bundles correct gegenereerd

2022-11-14 15:21 UTC, jduwel commented
Getest met Zelfmetingen Testmateriaal en MP9-2 overigens
Regressie met overige materialen misschien nog wijs om te doen

2022-11-16 11:07 UTC, merged