Convert fixtures from XML to JSON
Nictiz/Nictiz-tooling-testscripts pull request #32
Opened 2022-12-03 21:47 UTC by pieter-edelman-nictiz

Dit is wat mij betreft hoe de conversie zou moeten werken. Het komt hierop neer:
- Tijdens de NTS-build, tijdens het controleren op aanwezigheid van fixtures, wordt er een lijst bijgehouden van fixtures die missen in JSON-formaat maar die wel bestaan in XML. Die lijst wordt vertaald naar de _output_-folder, want dat zijn de fixtures die een narrative bevatten.
- Daarna worden narratives gegenereerd in de output folder.
- Na de narrative generation wordt de lijst doorgegeven aan de "convertXmlToJson" stap en daar wordt alles op die lijst geconverteerd.

Beperkingen:
- Hoofdlettergevoeligheid van bestandsnamen. Als je niet "json" en "xml" gebruikt, loopt de boel in het honderd.
- Je moet in je build.properties ook een 'fhir.version' (STU3/R4) opnemen, anders weet de converter niet wat hij moet gebruiken.
- Je krijgt er een hoop ANT/IVY-meldingen bij waar je geen chocola van kan maken.

Dingen die wél netjes zijn weggewerkt:
- NTS-conversie en JSON-conversie zijn grotendeels onafhankelijk van elkaar. Het NTS-buildscript weet hoe het de lijst moet bijhouden, maar doet dat alleen als er bestandsnaam voor die lijst wordt meegegeven.
- Als er niks op de lijst komt, wordt de "convertXmlToJson"-stap stilzwijgend overgeslagen.

Documentatie ontbreekt nog gedeeltelijk en er komt nog een pull request vanuit het Nictiz-testscripts-repo om dit in actie te zien. Dus vooralsnog een draft PR.

2022-12-05 10:23 UTC, jduwel requested changes
Doesn't work on my machine.
Edited tool.version in build-nts-single to `ConvertBundles` and ran SelfMeasurments Cert:
```
[echo] Converting XML fixtures to JSON
     [java] Java Result: 1
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:1: error: package ca.uhn.fhir.context does not exist
     [echo] import ca.uhn.fhir.context.FhirContext;
     [echo]                           ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:2: error: package ca.uhn.fhir.parser does not exist
     [echo] import ca.uhn.fhir.parser.IParser;
     [echo]                          ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:65: error: cannot find symbol
     [echo]         FhirContext context = null;
     [echo]         ^
     [echo]   symbol:   class FhirContext
     [echo]   location: class ConvertToJson
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:67: error: cannot find symbol
     [echo]             context = FhirContext.forDstu3();
     [echo]                       ^
     [echo]   symbol:   variable FhirContext
     [echo]   location: class ConvertToJson
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:68: error: package org.hl7.fhir.dstu3.formats does not exist
     [echo]             xmlParser = new org.hl7.fhir.dstu3.formats.XmlParser();
     [echo]                                                       ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:70: error: cannot find symbol
     [echo]             context = FhirContext.forR4();
     [echo]                       ^
     [echo]   symbol:   variable FhirContext
     [echo]   location: class ConvertToJson
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:71: error: package org.hl7.fhir.r4.formats does not exist
     [echo]             xmlParser = new org.hl7.fhir.r4.formats.XmlParser();
     [echo]                                                    ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:74: error: cannot find symbol
     [echo]         IParser jsonParser = context.newJsonParser();
     [echo]         ^
     [echo]   symbol:   class IParser
     [echo]   location: class ConvertToJson
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:84: error: package org.hl7.fhir.dstu3.model does not exist
     [echo]                     org.hl7.fhir.dstu3.model.Resource resource = ((org.hl7.fhir.dstu3.formats.XmlParser)xmlParser).parse(XML);
     [echo]                                             ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:84: error: package org.hl7.fhir.dstu3.formats does not exist
     [echo]                     org.hl7.fhir.dstu3.model.Resource resource = ((org.hl7.fhir.dstu3.formats.XmlParser)xmlParser).parse(XML);
     [echo]                                                                                              ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:87: error: package org.hl7.fhir.r4.model does not exist
     [echo]                     org.hl7.fhir.r4.model.Resource resource = ((org.hl7.fhir.r4.formats.XmlParser)xmlParser).parse(XML);
     [echo]                                          ^
     [echo] C:\Users\144189-ADM\Documents\Git\Nictiz-testscripts\lib\Nictiz-tooling-testscripts\convertXmlToJson\ConvertBundles\java\ConvertToJson.java:87: error: package org.hl7.fhir.r4.formats does not exist
     [echo]                     org.hl7.fhir.r4.model.Resource resource = ((org.hl7.fhir.r4.formats.XmlParser)xmlParser).parse(XML);
     [echo]                                                                                        ^
     [echo] 12 errors
     [echo] error: compilation failed
```

2022-12-05 10:23 UTC, jduwel commented on generate/ant/GetTarget.java
> +}
This file isn't referenced anywhere?

2022-12-05 10:23 UTC, jduwel commented on generate/README.md
> +Within the `@href` attribute of `nts:fixture`, the parameter `{$_FORMAT}` can be used to automatically output the format (either `xml` or `json`) the fixture is expected to be in. See the section bel
There doesn't seem te be a 'section below'

2022-12-05 10:23 UTC, jduwel commented on convertXmlToJson/ant/build.xml
> +      to be done.
But you create a `tempfile` in `build-multiple` and `build-single`, which is the process that is always used. How would one prevent this file from being created if you do not want the conversion?

2022-12-05 10:32 UTC, pieter-edelman-nictiz commented on generate/ant/GetTarget.java
> +}
Indeed, it shouldn't be included.

2022-12-05 10:34 UTC, pieter-edelman-nictiz commented on convertXmlToJson/ant/build.xml
> +      to be done.
`build-multiple` and `build-single` are the files that include this build file, they are not part of the "neutral" tool chain in the repo. So that's the entire point.

2022-12-05 10:54 UTC, jduwel commented on convertXmlToJson/ant/build.xml
> +      to be done.
Which makes this option kind of hypothetical? Wouldn't it be more transparent to just create the tempfile here then? If I'm correct it would remain empty anyways if no conversion needs to be done by the rules that are defined by the process (json-fixture that does not exist referenced, but xml-variant exists).

If I'm correct you would end up in this situation only when you plan on creating the json-fixtures yourself, but haven't done so yet, but the build fails anyways? Which would serve as a reminder for you to create those fixtures I guess,

If you do not want the conversion to happen for some other reason, wouldn't it be more transparent to make it skip based on a property being set?

2022-12-05 20:19 UTC, pieter-edelman-nictiz commented
> Doesn't work on my machine. Edited tool.version in build-nts-single to `ConvertBundles` and ran SelfMeasurments Cert:
> 

There was a type in the ANT file. Could you try again?

2022-12-05 20:21 UTC, pieter-edelman-nictiz commented on generate/README.md
> +Within the `@href` attribute of `nts:fixture`, the parameter `{$_FORMAT}` can be used to automatically output the format (either `xml` or `json`) the fixture is expected to be in. See the section bel
Yeah, I wanted to get your opinion on the approach first.

2022-12-06 10:19 UTC, pieter-edelman-nictiz commented on convertXmlToJson/ant/build.xml
> +      to be done.
I don't quite follow. For _this_ build file, it's only relevant if there is input to convert or not. If the file is empty _or_ absent, nothing is done. What use is there to create the file anyway and leave it empty?

For the NTS build file, it is relevant to know if it should fail on missing JSON fixtures or write them down for autoconversion. This is done by passing it a file to write the paths of fixtures to convert.

The consumers of these build files, that is `build-single` and `build-multiple`, include the step of autoconversion, so they define the file to write the fixture paths to. If you would want a flag to skip autoconversion, it should be defined in these files.

2022-12-07 09:09 UTC, jduwel commented
Got difference in whitespace output, committed here: https://github.com/Nictiz/Nictiz-testscripts/commit/b5cd1b3c5d56c3c5c0d6fc83ad4aaec727c9c282

2022-12-07 09:58 UTC, pieter-edelman-nictiz commented on convertXmlToJson/ant/build.xml
> +      to be done.
To the user of NTS in the Nictiz-testscripts, there is a single tool chain. This is built up from multiple back-ends, but that's irrelevant to the user in _that_ repo -- `build-single` and `build-multiple` are the truth there. There is no situation where conversion is skipped.

But it is not unimanginable that this particular tool is used in other tool chains. Or that the NTS build is used without this tool, or the narrative generator for that matter. This would be made impossible when building a monolithic NTS toolchain.

The reason `reference.file` is not used is that it is a per-project file. `convert.to.json.file` collects all information across projects.

2022-12-09 08:45 UTC, jduwel approved these changes

2022-12-09 08:47 UTC, merged