Performance refactor
Nictiz/Nictiz-tooling-testscripts pull request #39
Opened 2023-10-31 10:22 UTC by jduwel

2023-11-27 20:29 UTC, pieter-edelman-nictiz requested changes

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +        <attribute name="target.dir" default="#default" description="The name of the target to build; choose '#default' to build the default target."/>
I forgot why you use `<java>` rather than `<xslt>`. Could you add a comment to that?

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> -                            <saxon-transform style="${xslt.dir}/generateTestScript.xsl" in="@{nts.file}" out="@{output.dir}/${nts.file.newname}">
The "saxon-transform" macrodef is now effectively obsolete, but it's still defined and used for the generateLoadResources transformation. I think it's better to change that one as well and remove the macrodef.

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/generateTestScript.xsl
> +    <xsl:template name="substring-before-last">
I would suggest to make this a "private" function starting with an underscore and move it to the bottom of the file. And maybe turn it into a function?

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/generateTestScript.xsl
>      exclude-result-prefixes="#all">
"generateTestScript" is probably not the best name anymore, as it now transforms an entire folder of TestScripts. So ... "generateTestScriptFolder"?

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/generateTestScript.xsl
> +    <xsl:param name="target.dir" select="'#default'"/>
I'm not too happy with this name change. "target" is also what we use for "additional targets" and is not always a dir ("#default").

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/generateTestScript.xsl
> +    <xsl:template match="/" name="initialTemplate">
Could be a more descriptive name, like "buildFilesInTargetFolder"

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/processFixtures.xsl
> +    <xsl:template match="/" name="initialTemplate">
Same as for the other files, I think "initialTemplate" is not too descriptive of a name. Maybe something like "processFixturesInFolder"?

2023-11-27 20:29 UTC, pieter-edelman-nictiz commented on generate/xslt/collectReferences.xsl
> +    <xsl:template match="/" name="initialTemplate">
"processFilesInFolder"?

2023-12-07 15:37 UTC, jduwel commented on generate/ant/build.xml
> +        <if>
Didn't try that one. Seems to work!

2023-12-07 15:40 UTC, jduwel commented on generate/ant/build.xml
> +        <attribute name="target.dir" default="#default" description="The name of the target to build; choose '#default' to build the default target."/>
Done

2024-05-17 11:39 UTC, merged