loadRes-fixes: various fixes following GPData
Nictiz/Nictiz-tooling-testscripts pull request #4
Opened 2020-11-10 14:28 UTC by jduwel

GPData liet wat bugs zien:

De volgende loadresources.exclude was gewenst:
`loadresources.exclude = _reference/resources-query-send/medmij-gpdata-observation-contact*-S.xml,_reference/resources-query-send/medmij-gpdata-observation-contact*-O.xml`

Dus comma separated én met * wildcards, omdat je anders vanuit een automatisch gegenereerde map fixtures een handmatige sorteerstap moet volgen (of alle individuele fixtures in loadresources.exclude moest toevoegen. Comma separated werkte uberhaupt niet, omdat de originele situatie een sequence (true, false) binnen de blokhaken teruggaf in plaats van 1 boolean. Daarnaast naar regex gewisseld om de wildcard mogelijk te maken.

Daarnaast werd 1 gegenereerd id langer dan 64 karakters. Is substring() voldoende of is dat 'te dom' (moet er nog op uniqueness worden gecontroleerd)?

2020-11-10 15:22 UTC, jduwel commented
Ik heb net iets te lang geprobeerd om het voorkomen van loadResources genereren in ANT te voorkomen, maar dit werd a) omslachtig en b) je was een stukje logica aan het herhalen wat in generateLoadResources.xsl al aanwezig was. Vandaar een ietwat ranzige omweg gekozen: bij afwezigheid van fixtures een lege output genereren en die dan in ANT weer verwijderen.

2020-11-11 10:52 UTC, pieter-edelman-nictiz requested changes

2020-11-11 10:52 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +            <if>
Het is inderdaad niet zo'n fraaie methode, maar ik denk dat een nette methode disproportioneel veel tijd kost en niet veel oplevert. Misschien nog een optie om over na te denken: het XSLT-script wel een TestScript laten genereren, en checken of daar fixtures in aangehaald worden. Dat is wellicht robuuster dan erop vertrouwen dat het bestandje helemaal geen content bevat.

2020-11-11 11:08 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
De behoefte is ontstaan omdat er daadwerkelijk een id gegenereerd werd dat te lang was bij GPData en het proces gestopt werd. `gpdata-medicationrequest-contact06-paracetamol-codein` werd `MedicationRequest-gpdata-medicationrequest-contact06-paracetamol-codein`. Dus ondanks de smell is hier niets mis volgens mij, ik zou ook niet vanuit dit script beperkingen op de gebruiker willen opleggen (sowieso moet de error message dan meer informatie geven).

Ik zou dan toch gaan voor 2 - maar niet door checks of toevoegingen of iets dergelijks. Het is een intern id, dus ik zou generate-id() gebruiken voor iedere fixture denk ik. Volgens mij zijn die a) gegarandeerd uniek is maar b) wel hetzelfde als je hem meerdere keren genereert op dezelfde fixture.

2020-11-11 11:11 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
```
<xsl:template name="generateFixtureId" as="xs:string">
        <xsl:value-of select="generate-id(.)"/>
</xsl:template>```

geeft

```<fixture id="d362e2">
...
   </fixture>````

Het zijn inderdaad unieke id's. Wel een stuk minder menselijk leesbaar.

2020-11-11 11:28 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Ik zou dan ook wel de driemaal xsl:sort die voorkomt mee aanpassen:
```
<xsl:for-each select="$fixtures">
                        <xsl:sort select="lower-case(concat(local-name(), '-', f:id/@value))"/>
...
```
anders is er in het resultaat niet zo goed een touw aan vast te knopen wat er gebeurt. Sorteren op bestandsnaam (of pad) is dan logischer.

2020-11-11 11:34 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Ik kan er wel mee leven. Het is gegarandeerd een alfanumeriek id volgens de XSLT-spec, dus compatibel met FHIR id. In de praktijk blijft het ook wel binnen de limiet van 64 karakters. De generateFixtureId-template kan dan helemaal weg.
Nog wel een leuke feature: een check of de id's van fixtures aan de eisen voldoen. Ik schiet wel even een ticket in :D

2020-11-11 11:35 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Waarom zou je per se willen sorteren?

2020-11-11 11:37 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Misschien toch iets als
```
<xsl:template name="generateFixtureId" as="xs:string">
        <xsl:variable name="uniqueId" select="generate-id(.)"/>
        <xsl:variable name="normalizedId" select="replace(f:id/@value, '\s', '')"/>
        <xsl:variable name="fixtureId" select="substring(concat($uniqueId, '-', local-name(), '-', $normalizedId),1,64)"/>
</xsl:template>
```
voor het menselijk leesbare? Ben met MP bezig en met alleen generate-id's is het toch wel lastig controleren wat er allemaal aan de hand is (ook in TouchStone achteraf waarschijnlijk).

2020-11-11 11:39 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Re: sorteren.

Niet. Kan net goed weg, volgorde is niet van belang. (Plus: waarschijnlijk is de default volgorde die in de collection en dus filesystem)

2020-11-11 12:53 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Wat vind je hiervan? Best of both worlds?
```xml
    <xsl:template name="generateFixtureId" as="xs:string">
        <xsl:variable name="normalizedId" select="replace(f:id/@value, '\s', '')"/>
        <xsl:variable name="fixtureId" select="concat(local-name(), '-', $normalizedId)"/>
        
        <xsl:choose>
            <xsl:when test="matches($fixtureId, '^[A-Za-z0-9\-\.]{1,64}$')">
                <xsl:value-of select="$fixtureId"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:value-of select="substring(concat(local-name(), '-', generate-id(.), '-', $normalizedId),1,64)"/>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
```

2020-11-11 13:11 UTC, jduwel commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Dit werkt alleen gegarandeerd als HIT-3 opgelost is. Dus daar kunnen we op zich wel op vooruit lopen denk ik ;). Is in ieder geval het meest vriendelijk.

2020-11-11 13:16 UTC, jduwel commented on generate/ant/build.xml
> +            <if>
Ik heb dit geprobeerd in ANT, maar ik krijg het niet (binnen normale tijd) voor elkaar. loadresources output als xmlproperty inladen en kijken of TestScript.fixture(id) bestaat/gevuld is zou moeten werken, maar dat doet het niet. Dus ik wou het eigenlijk hierbij laten voor dit moment.

Zowel met een <if><isset> statement als met:
```
            <local name="TestScript.fixture(id)"/>
            <xmlproperty file="${loadresources.file}"/>
            
            <delete dir="${loadresources.file.dir}" unless:set="${TestScript.fixture(id)}"/>
```
Verwijdert altijd de loadresources dir - ook als ${TestScript.fixture(id)} heel duidelijk gevuld is.

Beide opties (<if> en unless:set) komen uit de Ant-contrib library. Misschien gaat dat niet met local properties om zoals ik dat zou willen, maar dat is niet echt te controleren. Er wordt namelijk eerder al NTS-files als xmlproperty ingeladen, misschien interfereert dat.

2020-11-11 13:38 UTC, pieter-edelman-nictiz commented on generate/ant/build.xml
> +            <if>
Laten we het maar zo houden. Ik heb het via HIT-5 op de backlog gezet om nog eens over na te denken.

2020-11-11 13:47 UTC, pieter-edelman-nictiz commented on generate/xslt/generateLoadResources.xsl
> +        <xsl:variable name="fixtureId" select="substring(concat(local-name(), '-', $normalizedId),1,64)"/>
Ik heb dit gelijk doorgevoerd, want dan kunnen we die normalization-stap er ook weer uit halen.

2020-11-11 14:50 UTC, pieter-edelman-nictiz approved these changes

2020-11-11 16:17 UTC, merged